### ISSUE TITLE
aborts when no modules present

### ISSUE THREAD

**Issue by lockbox** [orhun/kmon#138]
in this case under lxc on a chromebook (and probably on generic linux in a few other cases eg with no runtime modules) there is no `/proc/modules`, so this panic's. In this case could it just return and empty string so it would not panic, and then show an empty set of modules? 

https://github.com/orhun/kmon/blob/3ed516fcbfe6600d27287e49545f023e9736a200/src/kernel/lkm.rs#L117-L118

**Comment by orhun** [comment]
Hey, thanks for reporting!

> In this case could it just return and empty string so it would not panic, and then show an empty set of modules?

Yes I agree. Would you be interested in submitting a PR to fix this?

**Comment by eld4niz** [comment]
hey, @orhun. I tried changing that mentioned line to something like this:

```rust
let modules_content = util::exec_cmd("sh", &["-c", &module_read_cmd]).unwrap_or_else(|_| String::new());
```

should I also add few lines for parsing part?

**Comment by lockbox** [comment]
Would also probably be worth adding a log message or something since the display is just blank

**Comment by lockbox** [comment]
> hey, @orhun. I tried changing that mentioned line to something like this:
> 
> ```rust
> let modules_content = util::exec_cmd("sh", &["-c", &module_read_cmd]).unwrap_or_else(|_| String::new());
> ```
> 
> should I also add few lines for parsing part?

Thanks, saves me the time doing an MR lol🙏
