### ISSUE TITLE
Support for low-level module handling with insmod/rmmod

### ISSUE THREAD

**Issue by tpiekarski** [orhun/kmon#15]
**Is your feature request related to a problem? Please describe.**
The current way to load modules from within kmon is based upon modprobe. modprobe requires modules being inside /lib/modules/$(uname -r). This requirement having to install modules into that directory and update dependency tree with depmod is sometimes cumbersome. And to install some early development stage or experimental modules into the system should not be required.

**Describe the solution you'd like**
Offer a way to use insmod and rmmod for loading/unloading module independent of modprobe and without automatic dependent module handling. A possible implementation could be to try loading/unloading module with insmod/rmmod after modprobe failed. 

On second thought kmon could determine what to use if there is a filename with a .ko suffix provided. insmod require the full filename and modprobe only loads a module by its module name and defined aliases.

**Describe alternatives you've considered**
None, because loading a module with a path and a filename is not possible with modprobe.

**Additional context**
None

When we come to terms if and how this feature could be implemented, I would like to provide a PR.

**Comment by orhun** [comment]
That's totally reasonable :+1: 

> A possible implementation could be to try loading/unloading module with insmod/rmmod after modprobe failed.

I think it can be implemented in a easier and more convenient way. Like:

> kmon could determine what to use if there is a filename with a .ko suffix provided.

It's feasible, also a good idea.

Like you suggested, this feature should be implemented to load early development stage or experimental modules.

**Comment by tpiekarski** [comment]
Nice, I'll prepare a PR for review and discussion.
