### ISSUE TITLE
cannot use '?' in regex search

### ISSUE THREAD

**Issue by omnivagant** [orhun/kmon#179]
since the 1.7.0 release, and #178, it is possible tou use regex in the search bar, if started with `kmon --regex`

however, pressing `?` will open the `Help` view and exit the search box, making it impossible to use `?` in your regex

**Comment by orhun** [comment]
Thanks for reporting! This should be fixed in 139db020a18b6e17f4cc09ce5e8e54ee59bbddd3 now
