### ISSUE TITLE
Rust Version: 1.44.1 | build error >> error[E0277]: the trait bound `app::Block: enum_iterator::IntoEnumIterator` is not satisfied

### ISSUE THREAD

**Issue by denegny** [orhun/kmon#18]
**Describe the bug**
build halt with two error in compile

`.error[E0277]: the trait bound `app::Block: enum_iterator::IntoEnumIterator` is not satisfied
  --> /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/kmon-1.2.0/src/app.rs:57:1
   |
57 | / enum_unitary! {
58 | |     #[derive(Copy, Debug, PartialEq)]
59 | |     pub enum Block {
60 | |         UserInput,
...  |
64 | |     }
65 | | }
   | |_^ the trait `enum_iterator::IntoEnumIterator` is not implemented for `app::Block`
   |
  ::: /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/enum-unitary-0.4.2/src/lib.rs:25:45
   |
25 |     + Bounded + ToPrimitive + FromPrimitive + IntoEnumIterator
   |                                               ---------------- required by this bound in `enum_unitary::EnumUnitary`
   |
help: trait impl with same name found
  --> /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/kmon-1.2.0/src/app.rs:57:1
   |
57 | / enum_unitary! {
58 | |     #[derive(Copy, Debug, PartialEq)]
59 | |     pub enum Block {
60 | |         UserInput,
...  |
64 | |     }
65 | | }
   | |_^
   = note: perhaps two different versions of crate `enum_iterator` are being used?
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `app::InputMode: enum_iterator::IntoEnumIterator` is not satisfied
  --> /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/kmon-1.2.0/src/app.rs:68:1
   |
68 | / enum_unitary! {
69 | |     #[derive(Copy, Debug, PartialEq)]
70 | |     pub enum InputMode {
71 | |         None,
...  |
74 | |     }
75 | | }
   | |_^ the trait `enum_iterator::IntoEnumIterator` is not implemented for `app::InputMode`
   |
  ::: /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/enum-unitary-0.4.2/src/lib.rs:25:45
   |
25 |     + Bounded + ToPrimitive + FromPrimitive + IntoEnumIterator
   |                                               ---------------- required by this bound in `enum_unitary::EnumUnitary`
   |
help: trait impl with same name found
  --> /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/kmon-1.2.0/src/app.rs:68:1
   |
68 | / enum_unitary! {
69 | |     #[derive(Copy, Debug, PartialEq)]
70 | |     pub enum InputMode {
71 | |         None,
...  |
74 | |     }
75 | | }
   | |_^
   = note: perhaps two different versions of crate `enum_iterator` are being used?
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `kmon v1.2.0`, intermediate artifacts can be found at `/tmp/cargo-installAiFsRB`

Caused by:
  could not compile `kmon`.

Caused by:
  process didn't exit successfully: `rustc --crate-name kmon --edition=2018 /home/art/.asdf/installs/rust/1.44.1/registry/src/github.com-1ecc6299db9ec823/kmon-1.2.0/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=e545f8d8bd33e82c -C extra-filename=-e545f8d8bd33e82c --out-dir /tmp/cargo-installAiFsRB/release/deps -L dependency=/tmp/cargo-installAiFsRB/release/deps --extern bytesize=/tmp/cargo-installAiFsRB/release/deps/libbytesize-dfd1367e617f44fb.rlib --extern clap=/tmp/cargo-installAiFsRB/release/deps/libclap-b41fe8ef718cacb2.rlib --extern clipboard=/tmp/cargo-installAiFsRB/release/deps/libclipboard-33c23f869a4787d3.rlib --extern colorsys=/tmp/cargo-installAiFsRB/release/deps/libcolorsys-79f20d204a5d02d2.rlib --extern enum_iterator=/tmp/cargo-installAiFsRB/release/deps/libenum_iterator-eec005336cf21fd6.rlib --extern enum_unitary=/tmp/cargo-installAiFsRB/release/deps/libenum_unitary-08f4fb19923cffaf.rlib --extern termion=/tmp/cargo-installAiFsRB/release/deps/libtermion-2e03e248c2193d20.rlib --extern tui=/tmp/cargo-installAiFsRB/release/deps/libtui-b600972d1b9b84b2.rlib --extern unicode_width=/tmp/cargo-installAiFsRB/release/deps/libunicode_width-f22b9e6fd9fe1f27.rlib --cap-lints allow` (exit code: 1)`

**To Reproduce**
1. Run with '...' parameters
2. Use the '....' feature
3. Select the '....'

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**System (please complete the following information):**
 - OS Information: Kernel: 5.4.0-37-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8
  Distro: Linux Mint 19.3 Tricia
 - Rust Version: 1.44.1
 - Project Version:last

**Additional context**

**Comment by orhun** [comment]
This issue is fixed by 090c331aea46910edc222967ef5bd6787d739ed7 in v1.3.0 release.
