### ISSUE TITLE
Add string "kmod" to man 8 so it appears via apropos/man -k

### ISSUE THREAD

**Issue by Strykar** [orhun/kmon#24]
**Is your feature request related to a problem? Please describe.**
I often forget the name of kmon (not to say it isn't an intuitive name) and try to find it in a terminal via `apropos`/`man -k `using the string `kmod` which does not list `kmon`.

**Describe the solution you'd like**
Add the string `kmod` to the man page under Name/Description `like for managing the Linux kernel modules (kmod)`

**Describe alternatives you've considered**
Patching the man page for my Arch install, I'd be happy to submit a PR if you fancy the idea

**Comment by orhun** [comment]
It's totally reasonable 👍🏼.  I'd be glad if you propose a pull request regarding to this issue.
