### ISSUE TITLE
"error: could not compile `syn`." on ARM64 Ubuntu

### ISSUE THREAD

**Issue by sanderjo** [orhun/kmon#3]
**Describe the bug**

On an ARM64 system (with 512MB RAM) running Ubuntu 18.04.4 LTS the `cargo install kmon` results in an error
```
   Compiling termion v1.5.5
   Compiling xcb v0.8.2
   Compiling clap v2.33.0
   Compiling tui v0.8.0
error: could not compile `syn`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name syn /home/sander/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.17/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="extra-traits"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=e2b1f5fd1c5e3388 -C extra-filename=-e2b1f5fd1c5e3388 --out-dir /tmp/cargo-installjPvAn0/release/deps -L dependency=/tmp/cargo-installjPvAn0/release/deps --extern proc_macro2=/tmp/cargo-installjPvAn0/release/deps/libproc_macro2-941181b9f57e249a.rmeta --extern quote=/tmp/cargo-installjPvAn0/release/deps/libquote-e10e308aa35807a2.rmeta --extern unicode_xid=/tmp/cargo-installjPvAn0/release/deps/libunicode_xid-20d847053c8b7f62.rmeta --cap-lints allow --cfg syn_disable_nightly_tests` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `kmon v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installjPvAn0`

Caused by:
  build failed
sander@nanopineo2:~/git/kmon$ 
```

Might be related to / same as https://github.com/rust-lang/rust/issues/56501

**To Reproduce**
`cargo install kmon`

**Expected behavior**
A clean compile

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/1273502/78227835-2faa5b00-74ce-11ea-880f-191d101c7045.png)

**System (please complete the following information):**
 - OS Information: Ubuntu 18.04.4 LTS
 - Rust Version: rustc 1.39.0
 - Project Version: kmon 1.0.0

**Additional context**
Might be caused by low RAM, or https://github.com/rust-lang/rust/issues/56501 ?

**Comment by Jannik2099** [comment]
Compiles fine for me with rustc 1.42.0 on Gentoo arm64

**Comment by sanderjo** [comment]
> Compiles fine for me with rustc 1.42.0 on Gentoo arm64

How much RAM do you have in that system?

**Comment by Jannik2099** [comment]
4GB with 12GB swap. I'm pretty sure your process got killed by OOM killer or similar, it shows SIGKILL after all

**Comment by sanderjo** [comment]
Ah ... OOM leads to SIGKILL? 

I just checked dmesg, and there are "Out of memory" lines, but that was after disabling swap. I will recheck dmesg with the (tiny) swap on again.

**Comment by sanderjo** [comment]
Ouch:

```
$ dmesg -T | grep "Out of memory" 
[Thu Apr  2 15:52:54 2020] Out of memory: Killed process 2829 (rustc) total-vm:365980kB, anon-rss:101964kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:576kB oom_score_adj:0
```
So a low-memory problem. 

Details: https://github.com/rust-lang/rust/issues/56501#issuecomment-607883962

I'll close this issue as it's not related to kmon.
