### ISSUE TITLE
Could not compile - "ld returned 1 exit status"

### ISSUE THREAD

**Issue by Incedis** [orhun/kmon#4]
**Describe the bug**
Tried to compile with cargo. 
got error compiling

/usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb
          /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status

/usr/lib64/libxcb.so.1 --> Installed  

**To Reproduce**
1. Run with 'cargo install kmon' 
2. See error

**Expected behavior**
A clear compilation

**System:**
 - OS Information: 5.5.11-200.fc31.x86_64 Fedora 31
 - Rust Version: rustc 1.42.0

**Comment by orhun** [comment]
Did you install the `libxcb-devel` package as stated [here](https://github.com/orhun/kmon#note)?

**Comment by Incedis** [comment]
thanks and apoligies for not reading properly. thanks for the software as well., very useful.
