### ISSUE TITLE
dmesg not showing output in the desgnated pane

### ISSUE THREAD

**Issue by unixbhaskar** [orhun/kmon#6]
**Describe the bug**
When invoked as normal user dmesg not showing the output in the designated pane.

**To Reproduce**
Run as a normal user.

**Expected behavior**
dmesg should show the output in the designated pane.

**Screenshots/Logs**
Attached a screenshot for your perusal.
![2020-04-06-105832_2390x768_scrot](https://user-images.githubusercontent.com/113643/78525724-9ba20180-77f5-11ea-9a7b-4ba439a83a59.png)

**System (please complete the following information):**
 - OS Information: Gentoo, Slackware-current
 - Rust Version: [e.g. 1.40.0]
 - Project Version: kmon-1.0.0
**Additional context**
Please note, only in Arch, it is showing properly. Now, I have cross check the binaries, used by this program ,i.e dmesg , kmod permissions and locations ... look sane to me...still..

**Comment by orhun** [comment]
Did you try to run kmon as root? It looks like a permission issue to me.

Additionally, [this](https://unix.stackexchange.com/questions/390184/dmesg-read-kernel-buffer-failed-permission-denied) might be helpful if that's the case.

**Comment by unixbhaskar** [comment]
> Did you try to run kmon as root? It looks like a permission issue to me.
> 
> Additionally, [this](https://unix.stackexchange.com/questions/390184/dmesg-read-kernel-buffer-failed-permission-denied) might be helpful if that's the case.

Suspected that! thanks, I will give a shot.

**Comment by unixbhaskar** [comment]
Okay looks alright with the sysctl parameter set, as you @orhun mentioned.

So, I am closing this thread, because it solves the trivialities.
